Add book library task
vovachebr/external-courses pull request #15
Opened 2018-12-09 07:25 UTC by vovachebr

2018-12-09 08:29 UTC, DairoGrey requested changes

2018-12-09 08:29 UTC, DairoGrey commented on src/ex16_MVC/public/js/BookLibrary.js
> +            .then(responce => {
Перенеси логику по получению данных из запроса в отдельную функцию, много дублирования

2018-12-09 08:29 UTC, DairoGrey commented on src/ex16_MVC/public/js/BookLibrary.js
> +    getBooks(filter) {
Я бы разделил получение всего списка книг и отфильтрованного на два метода.

2018-12-09 08:29 UTC, DairoGrey commented on src/ex16_MVC/public/js/BookLibraryController.js
> +        let filterQuery = filter ? "?filter=" + filter : "";
Контроллер не должен знать, как мы получаем данные. Это должно быть в модели.

2018-12-09 08:29 UTC, DairoGrey commented on src/ex16_MVC/public/js/BookLibraryController.js
> +            let filterQuery = filter ? "?match=" + filter : "";
Тоже в модель

2018-12-09 08:29 UTC, DairoGrey commented on src/ex16_MVC/routes/books.js
> +    response.setHeader('content-type', 'application/json');
Если используешь json, content-type не нужно указывать.

2018-12-09 17:45 UTC, vovachebr commented on src/ex16_MVC/routes/books.js
> +    response.setHeader('content-type', 'application/json');
возникает ошибка: TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["application/json"]

2018-12-09 17:46 UTC, vovachebr commented on src/ex16_MVC/public/js/BookLibraryController.js
> +            let filterQuery = filter ? "?match=" + filter : "";
перенесено

2018-12-09 17:46 UTC, vovachebr commented on src/ex16_MVC/public/js/BookLibraryController.js
> +        let filterQuery = filter ? "?filter=" + filter : "";
перенесено

2018-12-09 17:46 UTC, vovachebr commented on src/ex16_MVC/public/js/BookLibrary.js
> +    getBooks(filter) {
разделено

2018-12-09 17:46 UTC, vovachebr commented on src/ex16_MVC/public/js/BookLibrary.js
> +            .then(responce => {
Перенесена логика в отдельную функцию

2018-12-14 11:53 UTC, DairoGrey requested changes

2018-12-14 11:53 UTC, DairoGrey commented on src/ex16_MVC/public/js/BooksLibraryView.js
> +            booksList.append(bookDiv);
Сделай через DocumentFragment, будет лучше в плане repaint/reflow

2018-12-14 11:53 UTC, DairoGrey commented on src/ex16_MVC/routes/books.js
> +const books = [
Вынеси массив в отдельный файл, например, books.db.js

2018-12-14 11:53 UTC, DairoGrey commented on src/ex16_MVC/routes/books.js
> +    currentBook.title = title;
Можно сделать через _Object_.**assign**

2018-12-14 11:53 UTC, DairoGrey commented on src/ex16_MVC/routes/books.js
> +        resultBooks = resultBooks.filter(b => b.title.toLowerCase().includes(query.match.toLowerCase()));
> При вводе символов в строку поиска отобразить отфильтрованный список книг, у которых введенная подстрока встречается в **названии**, **имени автора** или среди **ключевых слов**.

2018-12-14 11:53 UTC, DairoGrey commented on src/ex16_MVC/routes/books.js
> +        case "most-popular":
Наверное, free

2018-12-15 07:47 UTC, vovachebr commented on src/ex16_MVC/public/js/BooksLibraryView.js
> +            booksList.append(bookDiv);
исправлено

2018-12-15 07:47 UTC, vovachebr commented on src/ex16_MVC/routes/books.js
> +const books = [
вынесено в отдельный файл

2018-12-15 07:47 UTC, vovachebr commented on src/ex16_MVC/routes/books.js
> +    currentBook.title = title;
исправлено

2018-12-15 07:48 UTC, vovachebr commented on src/ex16_MVC/routes/books.js
> +        resultBooks = resultBooks.filter(b => b.title.toLowerCase().includes(query.match.toLowerCase()));
доделано, используются ключевые слова в книгах (ввод строкой, разделяются запятой или пробелом) и используются при поиске.

2018-12-15 07:48 UTC, vovachebr commented on src/ex16_MVC/routes/books.js
> +        case "most-popular":
наверное....исправил

2018-12-18 11:17 UTC, DairoGrey approved these changes

2018-12-18 11:17 UTC, merged